@startuml
start
:Вікно авторизації;
:Введення логіну<
:Введення паролю<
:Підтвердження введених даних<
:Надсилання запиту на сервер;
:Обробка запиту;
if (Чи існує такий користувач?) then (Так)
    if (Чи має користувач права адміністратора?) then (Так)
        :Відображення особистого кабінету адміністратора>
    else(Ні)
        :Відображення особистого кабінету охоронця>
    endif
else(Ні)
    :Вивід повідомлення про збій>
endif
stop
@enduml