@startuml
left to right direction
Користувач --> (Авторизація)
(Авторизація) --> Адмін
(Авторизація) --> Охоронець
Охоронець -[#red]-> Сервер
Охоронець --> (Вихід)
Адмін -[#red]-> Сервер
Сервер -[#red]-> (Перегляд записів з камер)
Сервер -[#red]-> (Перегляд стану датчиків)
Адмін -[#blue]-> (Реєстрація нових охоронців)
Адмін -[#blue]-> (Видалення охоронців)
(Реєстрація нових охоронців) -[#blue]-> Сервер
(Видалення охоронців) -[#blue]-> Сервер
Адмін --> (Вихід)
@enduml
