@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
hide methods
hide stereotypes

table(Guardians) {
  primary_key(Login)
  Password
  AdminAccess
}

table(Sensors) {
  primary_key(Room)
  Status
}
@enduml
