@startuml
start
:Відображення списку охоронців;
:Вибір охоронця, якого необхідно видалити<
if (Чи є з'єднання з Базою даних?) then (Так)
    if (Чи має користувач права адміністратора?) then (Так)
    :Видалення охоронця з відповідного поля таблиці Guardians>
    else (Ні)
    :Вивід повідомлення про відсутність прав на видалення користувачів>
    endif
else (Ні)
    :Вивід повідомлення про збій>  
endif
stop
@enduml