@startuml
start
:Вікно перегляду камер;
:Вибір камери<
:Вибір часу запису<
:Надсилання запиту на сервер;
:Обробка запиту;
if (Дані про користувача є у БД?) then (Так)
    :Відображення запису>
else(Ні)
    :Повідомити адміністратора про несанкціонованого користувача>
endif
stop
@enduml