@startuml
start
:Надсилання запиту на сервер;
:Обробка запиту;
if (Дані про користувача є у БД?) then (Так)
    :Відображення стану датчиків>
else(Ні)
    :Повідомити адміністратора про несанкціонованого користувача>
endif
stop
@enduml